services:
  app:
    image: ghcr.io/redwane-ait-oukazzamane/support-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:XE
      - SPRING_DATASOURCE_USERNAME=C##support_system
      - SPRING_DATASOURCE_PASSWORD=support_password
      - SPRING_DATASOURCE_DRIVER=oracle.jdbc.OracleDriver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
    depends_on:
      - oracle

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  oracle-data: 